### ISSUE TITLE
1.0.4 Has no Windows 10 version

### ISSUE THREAD

**Issue by BlackArmsGeneral** [codemasterv/fPKG_Maker_GUI#5] opened 2022-01-03 00:06 UTC
Has Win10 support been dropped from this project?

**Comment by codemasterv** [comment] 2022-01-03 01:15
Sorry I should have mentioned it works for both now with no differences in files. Its just one version now.

**Comment by BlackArmsGeneral** [comment] 2022-01-03 01:18
![image](https://user-images.githubusercontent.com/28333404/147894234-16bf8adb-9a67-4ed1-b28a-c71d99170dad.png)
I get this error every time I launch on Win10

**Comment by codemasterv** [comment] 2022-01-03 01:29
Ill test and get back to you shortly. 

Thank you

**Comment by codemasterv** [comment] 2022-01-03 01:56
![image](https://user-images.githubusercontent.com/23326730/147895146-a7c776c8-8fe3-4711-bde6-ede15d92e8fd.png)

Its working on windows 10

Did you install Ubuntu 20.04 from the windows app store?

**Comment by BlackArmsGeneral** [comment] 2022-01-03 01:59
version 1.0.1 still works except it locks up when making fPKGs. And I mean actually locks up, I left it running for 15 hours and it still did nothing.

**Comment by codemasterv** [comment] 2022-01-03 02:10
Oh I think i know whats going on.

On the github page click the fpkg_gui_maker.exe and download directly/ manually. 

I think the issue is the new size of the .exe and githubs git clone limitation. 

For whatever reason it wont download that file and will show 1kb file size. it should be 48MB in size

**Comment by BlackArmsGeneral** [comment] 2022-01-03 02:17
![image](https://user-images.githubusercontent.com/28333404/147895755-3df5870c-136d-4636-a9dc-199e0e8bbee2.png)
Well that works. Also the exe is just names "_fpkg_maker.exe" I wonder if github doesn't like the underscore?

**Comment by codemasterv** [comment] 2022-01-03 02:19
Yeah thats the debug version

I will be uploading one right now without the underscore that is the release version.

Should fix the issue with it now downloading. Might have been because the debug is not signed but the release is.

The new one is 88kb is size

**Comment by codemasterv** [comment] 2022-01-03 02:26
Im marking this as resolved if you run into any other issues please feel free to open another report.

Thank you for bringing that to my attention

**Comment by codemasterv** [comment] 2022-01-03 02:26
issues resolved

**Closed by codemasterv** 2022-01-03 02:26 UTC
